### ISSUE TITLE
Running this plugin results in a massive **BUILD FAILED** error

### ISSUE THREAD

**Issue by nsadeh** [joshuamiller/react-native-template-cljs-krell-storybook#6]
Steps to reproduce:
1. run this plugin by copy-pasting the command from the README
2. Build the project using the command in package.json (cljs:build)
3. Install the Podfile stuff (using the command for Apple Silicon in my case)
4. Run the ios command

I get a massive error message that's bigger than my terminal history. Here's the end of it:

```
2023-08-02 00:25:04.405 xcodebuild[50429:9987236] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:0C5EB4F3-6C28-4027-8D46-EE67499B8710, OS:16.4, name:iPhone 14 Pro Max }
{ platform:iOS Simulator, id:0C5EB4F3-6C28-4027-8D46-EE67499B8710, OS:16.4, name:iPhone 14 Pro Max }
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/nsadeh/Library/Developer/Xcode/DerivedData/ThirdPlaceTemplate-crvyzunmwzctzncahvsbeuugajsr/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-Codegen.build/Objects-normal/arm64/FBReactNativeSpec-generated.o /Users/nsadeh/Desktop/clj-projects/ThirdPlaceTemplate/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec-generated.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-Codegen' from project 'Pods')
(1 failure)
```

**Comment by sharnik** [comment]
@nsadeh  It seems this is an [issue in react-native](https://github.com/facebook/react-native/issues/36794) that can be solved by upgrading to [one of the supported versions](https://github.com/facebook/react-native/issues/36794#issuecomment-1621532862). I'd suggest just updating the patch version to avoid the headache of a full react-native upgrade. 

For me updating to 0.70.13 (newest at the time amongst 0.70.x) solved this problem.

**Comment by joshuamiller** [comment]
@sharnik Awesome, thank you for catching this. I'm going to bump the patch version as recommended, then look into the full upgrade to keep up-to-date.

**Comment by nsadeh** [comment]
Amazing, thanks. Sorry I couldn't be more help than just the reporter, I am brand new to both React Native and ClojureScript.
